### ISSUE TITLE
Multiple sheets

### ISSUE THREAD

**Issue by arisliang** [mustaddon/ArrayToExcel#1]
Is there an example to export two lists in different sheets, and save to same excel file?

**Comment by mustaddon** [comment]
> Is there an example to export two lists in different sheets, and save to same excel file?

there is no such example.
this tool has simple functionality - one list to one excel file.

**Comment by arisliang** [comment]
thanks for the clarification

**Comment by mustaddon** [comment]
Multiple sheets in Version 2.0
```
var excel = list1.ToExcel(schema => schema
    .AddSheet(list2)
    .AddSheet(list3)
    .AddSheet(list4));
```
