### ISSUE TITLE
Question: Can I add formula to a cell

### ISSUE THREAD

**Issue by oshri551** [mustaddon/ArrayToExcel#2]
Hi,

Is there a way to add formula to a cell - currently i see it as a string / text?

**Comment by mustaddon** [comment]
There is no such way.

**Comment by oshri551** [comment]
The more accurate is hyperlink ... still not possible?

**Comment by mustaddon** [comment]
Any hyperlinks will be inserted as simple text.

**Comment by oshri551** [comment]
What do you think about this? 

Add a class:
```
    public class CellHyperlink
    {
        public string Url { get; set; }
        public string Text { get; set; }

        public CellHyperlink(string url = "", string text = "")
        {
            Url = url;
            Text = text;
        }
    }
```

Modify:
```
    static Cell GetCell(string? reference, object? value)
    {
        var dataType = GetCellType(value);
        var cell = new Cell
        {
            CellReference = reference,
            CellValue = GetCellValue(value),
            DataType = dataType,
            StyleIndex = dataType == CellValues.Date ? 2 : 0u,
        };

        if (value?.GetType() == typeof(CellHyperlink))
        {
            var cellLink = (CellHyperlink)value;
            cell.CellFormula = new CellFormula
            {
                Text = string.Format("HYPERLINK(\"{0}\",\"{1}\")", cellLink.Url, cellLink.Text)
            };
        }

        return cell;
    }
```
usage: 
```
    static IEnumerable<SomeItem> SomeItems = Enumerable.Range(1, 10).Select(x => new SomeItem
    {
        Prop1 = new CellHyperlink("http://www.theclash.com", "Radio Clash"),
        Prop2 = x * 1000,
        Prop3 = DateTime.Now.AddDays(-x),
    });
```

Maybe it's possible later to add support for other things too...

**Comment by mustaddon** [comment]
Looks good. Hyperlinks support will be added after the holidays.

**Comment by oshri551** [comment]
Great! 
Don't forget to change the cell style to look like a link :)

Do you think the changes will be in few days? (I want to use it in our project and prefer not to use a modified fork)

**Comment by mustaddon** [comment]
Changes will be on january 9th.

**Comment by mustaddon** [comment]
done - version 2.0.6
https://github.com/mustaddon/ArrayToExcel/blob/master/Examples/Example.ConsoleApp/Program.cs#L215

**Comment by oshri551** [comment]
Cool!! Thanks!

Closing this one and I will be happy to be a contributor for new features and if you have some items in your mind you want to add
