### ISSUE TITLE
Question: Making multiple lines inside a cell

### ISSUE THREAD

**Issue by oshri551** [mustaddon/ArrayToExcel#3]
Hi,

Any way with current implementation to create multiple lines inside a cell?

I've tried \r\n  which doesn't work.
After some exploration looks like we need "WrapText" enabled on the cells to make it work

`new CellFormat() { Alignment = new Alignment() { WrapText = true} }`
Tried to do this which didn't work:
![image](https://user-images.githubusercontent.com/13517229/154054105-1ef024d5-0f69-4055-9b2f-22f39be1f9b0.png)

on the other hand if i put on the header cells the WrapText  i see it is marked when opening the excel

Thanks!

**Comment by mustaddon** [comment]
Hi, 
WrapText added to v2.0.7
\n - works now
https://github.com/mustaddon/ArrayToExcel/blob/d8021c800c6da99675abb7819aba851806659a61/Examples/Example.ConsoleApp/Program.cs#L203

**Comment by oshri551** [comment]
Wow ... Thanks!!
closing the issue 💯
