### ISSUE TITLE
Generated file is empty in Libre Office Calc

### ISSUE THREAD

**Issue by DinuRoth** [mustaddon/ArrayToExcel#6]
I generate an .xlsx file like this:

var items = Enumerable.Range (1, 10).Select (x => new
{
    Prop1 = $"Text #{x}",
    Prop2 = x * 1000,
    Prop3 = DateTime.Now.AddDays (-x),
});

var excel = items.ToExcel ();
File.WriteAllBytes ("c:\\temp\\excel.xlsx", excel);

When I open the generated file in MS Excel or some online viewers, it's working fine. But in Libre Office Calc, all cells are empty.

**Comment by mustaddon** [comment]
fixed in v2.5.0
